version: '3.8'

services:
  web:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
